project_id = "cdavvahoqbgncnvqdopb"

[functions.green-api-webhook]
verify_jwt = false

[functions.keep-alive]
verify_jwt = false

[functions.meta-webhook]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.process-receipt]
verify_jwt = false

[functions.extract-transfer-amount]
verify_jwt = false
