import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { InvoiceWithItems } from "@/hooks/useInvoices";

const fmt = (n: number, currency = "USD") =>
  new Intl.NumberFormat("en-US", { style: "currency", currency }).format(n || 0);

export function generateInvoicePdf(invoice: InvoiceWithItems) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // Header bar
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 90, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text("INVOICE", margin, 55);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Invoice No: ${invoice.invoice_number}`, pageWidth - margin, 40, { align: "right" });
  doc.text(`Date: ${invoice.invoice_date}`, pageWidth - margin, 55, { align: "right" });
  if (invoice.due_date) {
    doc.text(`Due: ${invoice.due_date}`, pageWidth - margin, 70, { align: "right" });
  }

  // From / To
  doc.setTextColor(15, 23, 42);
  let y = 130;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("FROM", margin, y);
  doc.text("BILL TO", pageWidth / 2, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  y += 16;
  doc.text(invoice.from_company || "", margin, y);
  doc.text(invoice.to_client || "", pageWidth / 2, y);

  if (invoice.from_address) {
    y += 14;
    doc.text(doc.splitTextToSize(invoice.from_address, pageWidth / 2 - margin - 10), margin, y);
  }
  if (invoice.to_address) {
    doc.text(
      doc.splitTextToSize(invoice.to_address, pageWidth / 2 - margin - 10),
      pageWidth / 2,
      y
    );
  }

  if (invoice.from_email) {
    y += 14;
    doc.text(invoice.from_email, margin, y);
  }
  if (invoice.to_email) {
    doc.text(invoice.to_email, pageWidth / 2, y);
  }

  if (invoice.project_name) {
    y += 24;
    doc.setFont("helvetica", "bold");
    doc.text(`Project: `, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(invoice.project_name, margin + 50, y);
  }

  // Items table
  const tableStartY = y + 30;
  autoTable(doc, {
    startY: tableStartY,
    head: [["Description", "Qty", "Unit Price", "Total"]],
    body: invoice.items.map((it) => [
      it.description,
      String(it.quantity),
      fmt(Number(it.unit_price), invoice.currency),
      fmt(Number(it.quantity) * Number(it.unit_price), invoice.currency),
    ]),
    headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 10, cellPadding: 8 },
    columnStyles: {
      1: { halign: "center", cellWidth: 50 },
      2: { halign: "right", cellWidth: 90 },
      3: { halign: "right", cellWidth: 90 },
    },
    margin: { left: margin, right: margin },
  });

  // Totals
  // @ts-expect-error - lastAutoTable is added by autoTable
  let endY = doc.lastAutoTable.finalY + 20;
  const labelX = pageWidth - margin - 180;
  const valueX = pageWidth - margin;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Subtotal:", labelX, endY);
  doc.text(fmt(Number(invoice.subtotal), invoice.currency), valueX, endY, { align: "right" });

  if (Number(invoice.tax_rate) > 0) {
    endY += 16;
    doc.text(`Tax (${invoice.tax_rate}%):`, labelX, endY);
    doc.text(fmt(Number(invoice.tax_amount), invoice.currency), valueX, endY, { align: "right" });
  }

  endY += 22;
  doc.setDrawColor(200);
  doc.line(labelX, endY - 14, valueX, endY - 14);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Total Due:", labelX, endY);
  doc.text(fmt(Number(invoice.total_amount), invoice.currency), valueX, endY, { align: "right" });

  // Notes
  if (invoice.notes) {
    endY += 40;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("Notes", margin, endY);
    doc.setFont("helvetica", "normal");
    endY += 14;
    doc.text(doc.splitTextToSize(invoice.notes, pageWidth - margin * 2), margin, endY);
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(
    `Generated by Hisabaty • ${new Date().toLocaleDateString("en-US")}`,
    pageWidth / 2,
    pageHeight - 20,
    { align: "center" }
  );

  doc.save(`Invoice-${invoice.invoice_number}.pdf`);
}
